# -*- coding: utf-8 -*-
"""tarea ordenada.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1iP7syfSockCP7TJhK09yusaKJmR_OXIq
"""

#TAREA ORDENADA
#1 Escribí un programa que lea dos números por teclado y permita elegir entre 4 opciones en un menú:
#Mostrar una suma de los dos números
#Mostrar una resta de los dos números (el primero menos el segundo)
#Mostrar una multiplicación de los dos números
#Si elige esta opción se interrumpirá la impresión del menú y el programa finalizará
#En caso de no introducir una opción válida, el programa informará de que no es correcta.

n1 = float (input ("ingresa un numero: "))
n2 = float (input ("ingresa un numero: "))
print("tiene que elegir entre las 4 opciones")
print("la opcion A (SUMA n1 + n2)")
print("la opcion B (RESTA n1 - n2)")
print("la opcion C (MULTIPLICA n1 * n2)")
print("la opcion ESCAPE (sale del programa)")
print("En caso de no introducir una opción válida, el programa informará de que no es correcta.")
opciones = (input ("elija la opcion deseada: "))
if opciones == "A":
    print("RESULTADO", n1+n2 , "por que:", n1 , "mas" , n2 , "Es:", n1+n2)
elif opciones == "B":
    print("RESULTADO", n1-n2 , "por que:", n1 , "menos" , n2 , "Es:", n1-n2 )
elif opciones == "C":
    print("RESULTADO", n1*n2 ,"por que:", n1 , "por" , n2 , "Es:", n1*n2 )
elif opciones == "ESCAPE":
    print("fin del programa" )  
else:
    print("ingreso una opcion incorrecta las funciones son A B C ó ESCAPE")

#2)Escribí un programa que lea un número impar por teclado. 
#Si el usuario no introduce un número impar, debe repetirse el proceso hasta que lo introduzca correctamente.
print("debes ingresar un numero, si el numero es par sigue ejecutando hasta que ingreses un numero impar")
aD = float (input ("Ingresar un Numero: "))
while aD % 2 == 0 :
  aD1 = float (input ("Ingresar un Numero: "))
  if aD1 % 2 != 0:
    print("ingreso numero impar!!")
    break    
else:    
  print("ingreso numero impar")

#3) Escribí un programa que sume todos los números enteros impares desde el 0 hasta el 100:
sumatotal = 0
listaimpar = []
for numeros in range(0,101):
  if numeros % 2 != 0:
    sumatotal += numeros
    listaimpar.append(numeros)
print(sumatotal) 
#corroboro que sean impares
#print(listaimpar)
#sumo lista creada con impares
#print(sum(listaimpar))
#otra forma de resolver el ejercicio en una linea
#print(sum(range(1,100,2)))

#4 Escribí un programa que pida al usuario cuantos números quiere introducir. Luego lee todos los números y realiza una media aritmética:

cont = 0
suma = 0
cantidad = int (input ("Ingresar un Numero cantidad de veces: "))
while True :
  numerin = int(input ("Ingresar un Numero: "))
  cont += 1
  #print("cont",cont)
  suma += numerin
  #print("suma",suma)
  if cantidad <= cont:
    break
promedio = suma / cantidad
print("el promedio es: " , promedio )
print("Termino el programa")

#5 
#Escribí un programa que pida al usuario un número entero del 0 al 9, 
#y que mientras el número no sea correcto se repita el proceso.
# Luego debe comprobar si el número se encuentra en la lista de números y notificarlo:
lista = [1,3,6,9]
x = int(input("Ingrese un numero entero del 1 al 9: "))
if x in lista:
  print ("el numero que ingreso SI ESTA en la lista: ")
else: 
  print ("el numero que ingreso NO ESTA en la lista ")
  while True:
    x1 = int(input("ingrese un Numero entero del 1 al 9: "))    
    if x1 in lista:
      print ("ingreso un Numero de la Lista" , lista , "ingreso el numero: ", x1)
      break

#6 Utilizando la función range() y la conversión a listas genera las siguientes listas dinámicamente:
#1 a Todos los números del 0 al 10 [0, 1, 2, ..., 10]
#2 b Todos los números del -10 al 0 [-10, -9, -8, ..., 0]
#3 c Todos los números pares del 0 al 20 [0, 2, 4, ..., 20]
#4 d Todos los números impares entre -20 y 0 [-19, -17, -15, ..., -1]
#5 e Todos los números múltiples de 5 del 0 al 50 [0, 5, 10, ..., 50]
a=list(range(0,11))
print("lista a" , a)
b=list(range(-10,1))
print("lista b" , b)
c=list(range(0,21,2))
print("lista c" , c)
d=list(range(-19,0))
print("lista d" , d)
e=list(range(0,51,5))
print("lista e", e)

#7) Dadas dos listas, debes generar una tercera con todos los elementos que se repitan en ellas, 
#pero no debe repetirse ningún elemento en la nueva lista:

lista_1 = ["h",'o','l','a',' ', 'm','u','n','d','o']
lista_2 = ["h",'o','l','a',' ', 'l','u','n','a']
lista_3 = []
for letras in lista_1:
    if letras in lista_2 and letras not in lista_3:
        lista_3.append(letras)
print(lista_3)

