# -*- coding: utf-8 -*-
"""FunciónAñoBisiestoChiodini.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p7tEdCP4kZgLqxs78JxolXR9TIp1T-29
"""

#TAREA
#Se recuerda que los años bisiestos son múltiplos de 4, pero los múltiplos de 100 no lo son, aunque los múltiplos de 400 sí. 
#Estos son algunos ejemplos de posibles respuestas: 2012 es bisiesto, 2010 no es bisiesto, 2000 es bisiesto, 1900 no es bisiesto

def anio_bisiesto(anio):
  if type(anio) == int:    
    #bisiesto cuando es multiplo de 4 y no es multiplo de 100 o es multiplo de 4 y de 400
    if anio % 4 == 0 and (anio % 100 != 0 or anio % 400 == 0):
      print(f"El AÑO {anio} ES BISIESTO")
    else:
      print(f"El AÑO {anio} NO ES BISIESTO")  
  else:
    print("oye no has ingresado un numero en el parametro")
anio_bisiesto(1900)