# -*- coding: utf-8 -*-
"""Actividad 5 Chiodini.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wgqnDMcblLp4b5relKlR9Iu0Gcui_rTu
"""

#1 Realiza una función llamada area_rectangulo() que devuelva el área del rectángulo a partir de una base y una altura. 
#Calcula el área de un rectángulo de 15 de base y 10 de altura

def area_rectangulo(base,altura):
  area = base*altura
  print("el area es: ", area)
  return area
area_rectangulo(15,10)

#2 Realiza una función llamada area_circulo() que devuelva el área de un círculo a partir de un radio.
#calcula el area de un circulo de 5 de radio

def area_circulo(radio):
  calculo = (radio**2)*3.14159
  print(f"el area de un circulo de radio {radio} es {calculo}")
  return calculo
area_circulo(5)

#3 
#Realiza una función llamada relacion() que a partir de dos números cumpla lo siguiente:

#Si el primer número es mayor que el segundo, debe devolver 1.
#Si el primer número es menor que el segundo, debe devolver -1.
#Si ambos números son iguales, debe devolver un 0.

#Comprueba la relación entre los números: '5 y 10', '10 y 5' y '5 y 5'


def relacion(a,b):
  if a > b :
    print("devuelvo 1") 
    return 1  
  elif a < b : 
    print("devuelvo -1") 
    return -1  
  elif a == b :  
    print("devuelvo 0")
    return 0

relacion(5,10)

relacion(10,5)

relacion(5,5)

#4 Realiza una función llamada intermedio() que a partir de dos números, devuelva su punto intermedio:
def intermedio(a,b):
  print(f"el medio entre {a} y {b} es {(a+b)/2} ")
  return (a+b)/2
intermedio(-12,24)

#5Realizá una función llamada recortar() que reciba tres parámetros. El primero es el número a recortar, el segundo es el límite inferior y el tercero el límite superior. 
#La función tendrá que cumplir lo siguiente:

#Devolver el límite inferior si el número es menor que éste
#Devolver el límite superior si el número es mayor que éste.
#Devolver el número sin cambios si no se supera ningún límite.
#Comprueba el resultado de recortar 15 entre los límites 0 y 10

def recortar(numero,linf,lsup):
  if numero < linf:
    print("limite inferior: " , linf)
    return linf
  elif numero > lsup:
    print("Limite superior:  ", lsup) 
    return lsup
  else:
    print("devuelvo el mismo no se paso del rango", numero)
    return numero
recortar(15,0,10)

#Realiza una función separar() que tome una lista de números enteros y devuelva dos listas ordenadas.
# La primera con los números pares, y la segunda con los números impares:

pares=[]
impares=[]
lista1=[6,5,2,1,7]
#lista2=[100,260,353,430,509]
def separar(lista):
  for i in lista:    
    if i % 2 == 0 : 
      pares.append(i)
      pares.sort()
    else:
      impares.append(i)
      impares.sort()
  return print("termino la funcion separar numeros pares e impares de una lista y ordenar en lista, esto se imprime en el return") 

separar(lista1)  

print("la lista pares contiene!", pares)
print("la lista impares contiene!", impares)