# -*- coding: utf-8 -*-
"""Actividad N°6 Cuenta_FESAT_Chiodini.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XyUWgIE6Q11K344IBsySVgZvzD8vIaxI
"""

class Cuenta:
  def __init__ (self, nombre, saldo=0):
    self.nombre=nombre
    self.saldo=saldo
    if saldo < 0:
      print("saldo inicial negativo en cuenta")
  def mostrar(self):
    print(f"Datos de la cuenta: {self.nombre} con saldo de: {self.saldo}")
  def ingresar(self, montomas=0):
    self.montomas=montomas    
    if montomas >= 0:
      self.saldo+=self.montomas
      print("Usted ingresó", self.montomas, "y el saldo es" , self.saldo)
      return self.montomas
    #else:
     # print("ingreso un numero negativo, no hago nada", montomas)
  def retirar(self, monto_retirar=0):
    self.monto_retirar=monto_retirar
    self.saldo-=self.monto_retirar
    print("Usted Retiro", self.monto_retirar, "y el saldo es:", self.saldo)
    return self.monto_retirar
      

a1 = Cuenta("Maria Gabriela", 10)
a1.nombre
a1.mostrar()
a1.ingresar(5)
a1.retirar(1)
dario = Cuenta("Dario", 4000)
dario.mostrar()
dario.ingresar(9000)
dario.mostrar()
dario.retirar(400)
dario.mostrar()
#por dariochiodini