# -*- coding: utf-8 -*-
"""Actividad Cetaceo_ Chiodini_FESAT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NM4C9uKy_N3Gs7DKAnTCJTS2OnYU49aI
"""

class Mamifero:  
  def mamar(self, tiempo):
    self.tiempo=tiempo
    print(f"Da de mamar {self.tiempo} años")
    return self.tiempo
  def nacer(self, crias):
    self.crias=crias
    print(f"Tiene {self.crias} crias promedio")
    return self.crias
class AnimalMarino:  
  def nadar(self, velocidad):
    self.velocidad=velocidad
    print(f"nada a {self.velocidad} km por hora")
    return self.velocidad
class Cetaceo(Mamifero,AnimalMarino):
  peso = "mucho"
  def oceano(self, oceano):
    self.oceano=oceano
    print("vivo en el oceano" , self.oceano)
    return self.oceano

perro = Mamifero()
perro.mamar(1)
perro.nacer(5)
pez=AnimalMarino()
pez.nadar(10)
ballena=Cetaceo()
ballena.nadar(2)
ballena.nacer(5)