# Generated by Django 4.0.5 on 2022-06-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_comments_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
