# Generated by Django 4.0.5 on 2022-06-19 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0004_comments_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments',
            new_name='Comment',
        ),
    ]
